spring:
  application:
    name: hong-mq
  profiles:
    active: dev

  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

server:
  port: 9008
  servlet:
    context-path: /

#mybatis:
#  type-aliases-package: com.hong.mapper
#  mapper-locations: classpath:mapper/*.xml

debug: false