spring:
  application:
    name: hong-mq
  profiles:
    active: test

  http:
    encoding:
      charset: UTF-8

server:
  port: 9008
  servlet:
    context-path: /

#mybatis:
#  type-aliases-package: com.hong.mapper
#  mapper-locations: classpath:mapper/*.xml

debug: false